# Generated by Django 5.2.7 on 2026-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва роботи')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Текст тез')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('PENDING', 'На рецензуванні'), ('ACCEPTED', 'Прийнято'), ('REJECTED', 'Відхилено')], default='PENDING', max_length=10)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
