# Generated by Django 5.2.7 on 2026-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
