# Generated by Django 5.2.7 on 2026-03-27 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_initial'),
        ('submissions', '0003_submission_comments_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_comment', models.TextField(blank=True, verbose_name='Коментар до змін')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Історія версій',
                'verbose_name_plural': 'Історія версій',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='submission',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='parent_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Чернетка'), ('PENDING', 'На рецензуванні'), ('REVISION_REQUIRED', 'Потребує доопрацювання'), ('ACCEPTED', 'Прийнято'), ('REJECTED', 'Відхилено')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['conference', 'status'], name='submissions_confere_2bd225_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['author', 'is_latest'], name='submissions_author__39e9db_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-version'], name='submissions_version_5155ae_idx'),
        ),
        migrations.AddField(
            model_name='versionhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versionhistory',
            name='previous_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='versionhistory',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='submissions.submission'),
        ),
    ]
