# Generated by Django 5.2.7 on 2026-04-01 17:22

import submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_alter_conference_category'),
        ('submissions', '0005_submissionview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionview',
            options={'verbose_name': 'Перегляд тези', 'verbose_name_plural': 'Перегляди тез'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.submission_file_path, verbose_name='Файл'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionview',
            unique_together={('submission', 'user')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'is_latest'], name='submissions_status_f1f441_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['conference', 'status', 'is_latest'], name='submissions_confere_3f0b10_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionview',
            index=models.Index(fields=['submission', 'user'], name='submissions_submiss_3711e2_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionview',
            index=models.Index(fields=['viewed_at'], name='submissions_viewed__70aeb3_idx'),
        ),
    ]
