# Generated by Django 5.2.7 on 2026-04-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submission_archived_at_submission_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_archived',
        ),
    ]
