# Generated by Django 5.2.7 on 2026-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_remove_submission_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Дата, коли тезу було переміщено в архів', null=True, verbose_name='Дата архівації'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Чи знаходиться теза в архіві', verbose_name='В архіві'),
        ),
    ]
