# Generated by Django 5.2.7 on 2026-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('SUBMISSION_STATUS', 'Зміна статусу тези'), ('REVIEW_INVITE', 'Запрошення стати рецензентом'), ('GENERAL', 'Загальне повідомлення')], default='GENERAL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
