# Generated by Django 5.2.7 on 2026-04-01 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SUBMISSION_STATUS', 'Зміна статусу тези'), ('SUBMISSION_PENDING', 'Нова теза на рецензію'), ('REVIEW_INVITE', 'Запрошення стати рецензентом'), ('SUBMISSION_REVIEW', 'Результат рецензії'), ('COMMENT', 'Новий коментар'), ('COMMENT_REPLY', 'Відповідь на коментар'), ('VOTE', 'Голос за коментар'), ('GENERAL', 'Загальне повідомлення')], default='GENERAL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
    ]
