# Generated by Django 5.2.7 on 2026-04-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код верифікації'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата створення коду'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email підтверджено'),
        ),
    ]
