# Generated by Django 5.2.7 on 2026-03-27 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0002_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconferenceview',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='conferences.conference'),
        ),
        migrations.AddField(
            model_name='userconferenceview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['user', 'action_type'], name='recommendat_user_id_5af809_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['created_at'], name='recommendat_created_a758d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userconferenceview',
            unique_together={('user', 'conference')},
        ),
    ]
