# Generated by Django 5.2.7 on 2026-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('AI', 'Штучний інтелект'), ('WEB', 'Веб-розробка'), ('DATA', 'Аналіз даних'), ('SECURITY', 'Кібербезпека')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('submission_deadline', models.DateField()),
                ('conference_id', models.CharField(editable=False, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Очікує відповіді'), ('ACCEPTED', 'Прийнято'), ('REJECTED', 'Відхилено')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
