# Generated by Django 5.2.7 on 2026-03-27 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_conferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='review_conferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewerinvitation',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='conferences.conference'),
        ),
        migrations.AddField(
            model_name='reviewerinvitation',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reviewerinvitation',
            unique_together={('conference', 'reviewer')},
        ),
    ]
