# Generated by Django 5.2.7 on 2026-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='category',
            field=models.CharField(choices=[('MATH', 'Математика'), ('CS', 'Інформатика'), ('AI', 'Штучний інтелект'), ('WEB', 'Веб-розробка'), ('DATA', 'Аналіз даних'), ('SECURITY', 'Кібербезпека'), ('PHYSICS', 'Фізика'), ('BIOLOGY', 'Біологія'), ('CHEMISTRY', 'Хімія')], max_length=50),
        ),
    ]
