# Generated by Django 5.2.7 on 2026-04-09 14:32

import conferences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_alter_conference_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='additional_files',
            field=models.JSONField(blank=True, default=list, help_text='Список додаткових файлів (назва, URL, тип)', verbose_name='Додаткові файли'),
        ),
        migrations.AddField(
            model_name='conference',
            name='guidelines_file',
            field=models.FileField(blank=True, help_text='PDF файл з інструкціями для авторів', null=True, upload_to=conferences.models.conference_file_path, verbose_name='Інструкція для авторів'),
        ),
    ]
