# Generated by Django 5.2.7 on 2026-04-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='address',
            field=models.TextField(blank=True, help_text='Фізична адреса місця проведення конференції', null=True, verbose_name='Адреса проведення'),
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_type',
            field=models.CharField(choices=[('OFFLINE', 'Офлайн'), ('ONLINE', 'Онлайн'), ('HYBRID', 'Гібридний (офлайн + онлайн)')], default='ONLINE', help_text='Оберіть формат проведення конференції', max_length=20, verbose_name='Тип проведення'),
        ),
        migrations.AddField(
            model_name='conference',
            name='institution',
            field=models.CharField(blank=True, help_text='Назва навчального закладу або організації, що проводить конференцію', max_length=255, null=True, verbose_name='Навчальний заклад/Організація'),
        ),
        migrations.AddField(
            model_name='conference',
            name='online_link',
            field=models.URLField(blank=True, help_text='Zoom, Google Meet, або інше посилання для онлайн підключення', null=True, verbose_name='Посилання для онлайн участі'),
        ),
    ]
