# Generated by Django 5.2.7 on 2026-03-28 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_profile_public', models.BooleanField(default=True, help_text='Чи можуть інші користувачі бачити ваш профіль', verbose_name='Публічний профіль')),
                ('show_email', models.BooleanField(default=False, help_text='Чи показувати email у публічному профілі', verbose_name='Показувати email')),
                ('show_orcid', models.BooleanField(default=True, help_text='Чи показувати ORCID ID у публічному профілі', verbose_name='Показувати ORCID')),
                ('bio', models.TextField(blank=True, help_text='Коротка інформація про себе', null=True, verbose_name='Біографія')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Вебсайт')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('google_scholar', models.URLField(blank=True, null=True, verbose_name='Google Scholar')),
                ('profile_views', models.IntegerField(default=0, verbose_name='Переглядів профілю')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
